// import React from 'react'

const Resume = () => {
  return (
    <div className="container-fluid">
      <div className="row">
        <div className="col-md-2 col-md-offset-5" style={{fontSize: '42px', textAlign: 'center'}}>Zack Adams</div>
      </div>
      <br />
      <div className="row">
        <div className="col-lg-2 col-lg-offset-3 text-center">651.206.2992</div>
        <div className="col-lg-2 text-center">adams.z.d@gmail.com</div>
        <div className="col-lg-2 text-center">github: <a href="http://www.github.com/drzackyll" target="_blank" rel="noreferrer">@drzackyll</a></div>
      </div>
      <div className="row">
        <div className="col-lg-8 col-lg-offset-2">
          <div className="resume-grey"><h4>ABOUT</h4></div>
          <div>
          I am a software engineer who focuses on international development. I pursued development, peace, and conflict resolution academically, with the intention of being a practitioner on the programmatic side. Then, having developed an interest in coding, I sought to combine my interests with a career as a 'developer for good'. I was recently working for UNICEF on software that streamlines the way hundreds of country offices work with their partner organizations. Lately, my work has shifted to visualizing the valuable data generated by some of UNICEF's digital endeavors. R3D is an exciting project that will help to improve the way UNICEF communicates directly with beneficieries.
          </div>
          <br />
          <div>
            <div className="resume-grey"><h4>SKILLS AND LANGUAGES</h4></div>
            + JavaScript, Polymer, ReactJS, Redux, TypeScript, Microsoft Power BI, Apache Superset, SQL, HTML/CSS, Bootstrap<br />
            </div>
          <br />
          <div>
            <div className="resume-grey"><h4>EMPLOYMENT HISTORY</h4></div>
            <a href="http://www.unicef.org" target="_blank" rel="noreferrer"><b>UNICEF</b></a>, New York, NY<br />
            T4D Data Analyst and Software Engineer, January 2020 - present<br />
            + Founding member of <a href="https://superset.unicef.io/" target="_blank" rel="noreferrer">Realtime Data Driven Dashboards (R3D)</a> project<br />
            + Leading the 'presentation layer' (front end) of the project<br />
            + Created four prototype dashboards, iterating in conjunction with end user test groups<br />
            + Collaborating with project lead and backend engineer to identify opportunities for performance improvement<br />
            + Created a Superset tour to walk end users through functionality<br />
            + Rolling project out to 190+ RapidPro workspaces<br />
            <br />
            Software Engineer, <a href="https://etools.unicef.org/" target="_blank" rel="noreferrer">eTools</a>, August 2017 - December 2019<br />
            + Upgraded multiple software modules to Polymer 3<br />
            + Managed project to create a Security Incident Reporting system for UNICEF EMOPS.<br />
            + Executed complete rebuilds of several primary dashboard pages<br />
            + Created a reusable custom Polymer component that tracks analytics using Piwik/Matomo<br />
            + Maintain software with regular bug fixes and feature refinement and development<br />
            + Utilize Agile methodology to collaborate with backend developers and product owners for regular delivery of updates<br />
            + Write tests for many custom components<br />
            + Collaborate with designer to ensure consistency of styling across project areas<br />
          </div>
          <br />
          <div>
            <a href="http://www.episcopalchurch.org" target="_blank" rel="noreferrer"><b>The Episcopal Church</b></a>, New York, NY<br />
            Development Communications Manager, November 2012 - July 2016<br />
            + Managed the donor communications efforts of the nascent Development Office, including extensive work with our fundraising database, social media management, postal and email communications, and event support.<br />
            + Spearheaded the creation of a database of 600+ Episcopalians involved in post-earthquake relief efforts in Haiti, including creating a map of US-Haiti relationships.<br />
          </div>
          <br />
          <div>
            <b>Flattau Associates</b>, Washington, DC<br />
            Researcher, November 2011 - October 2012<br />
            + Monitored in-country news sources via LexisNexis.<br />
            + Prepared reports on governance and democracy in Kenya and Tanzania.<br />
          </div>
          <br />
          <div>
            <a href="http://www.usip.org" target="_blank" rel="noreferrer"><b>United States Institute of Peace</b></a>, Washington, DC<br />
            Research Assistant, August 2010 - September 2011<br />
            + Worked for the Academy for International Conflict Management and Peacebuilding during graduate school.<br />
            + Research and training assistant who prepared course materials for training military and civilian practitioners of conflict resolution.<br />
          </div>
          <br />
          <div>
            <div className="resume-grey"><h4>EDUCATION</h4></div>
            <a href="http://www.flatironschool.com" target="_blank" rel="noreferrer"><b>Flatiron School</b></a> - New York, NY - 2016<br />
            + Full Stack Web Development, Ruby on Rails and JavaScript immersive program<br />
          </div>
          <br />
          <div>
            <a href="http://www.american.edu" target="_blank" rel="noreferrer"><b>American University</b></a> - Washington, DC - 2011<br />
            + Master of Arts: International Peace and Conflict Resolution<br />
          </div>
          <br />
          <div>
            <a href="http://www.macalester.edu" target="_blank" rel="noreferrer"><b>Macalester College</b></a> - St. Paul, MN - 2007<br />
            + Bachelor of Arts: Double Major: International Studies, Political Science<br />
          </div>
        </div>
      </div>
    </div>
  )
}

export default Resume
