const Work = () => {
  return (
    <div className="container-fluid">
      <br />
      <div className="row">
        <div className="col-sm-4 col-sm-offset-2">
          <a href="https://superset.unicef.io/" target="_blank" rel="noreferrer">
            <img className="img-thumbnail" src="../../images/r3d-screen-shot.png" alt="UNICEF R3D Screen Shot" />
          </a>
        </div>
        <div className="col-sm-4">
          <a href="https://superset.unicef.io/" target="_blank" rel="noreferrer"><h4>Realtime Data Driven Dashboards (R3D) - UNICEF</h4></a>
          i worked to create the presentation layer of the R3D project. R3D is a data analysis and visualization project that harnesses the data generated by <a href="https://rapidpro.github.io/rapidpro/" target="_blank" rel="noreferrer">RapidPro</a> workspaces around the world. in collaboration with end user groups, i put together four prototypes, which we are rolling out in phases to 190+ workspaces.<br /><br />
        <b>built with:</b> apache superset <br /><br />
        <a href="/portfolio"><b>portfolio</b></a>
        </div>
      </div><hr />
      <div><br /></div>

      <div className="row">
        <div className="col-sm-4 col-sm-offset-2">
          <a href="https://superset.unicef.io/" target="_blank" rel="noreferrer">
            <img className="img-thumbnail" src="../../images/drp-screen-shot.png" alt="UNICEF R3D Screen Shot" />
          </a>
        </div>
        <div className="col-sm-4">
          <a href="https://drp.unicef.org/" target="_blank" rel="noreferrer"><h4>Donor Reporting Portal - UNICEF</h4></a>
          Donor Reporting Portal is an application that allows UNICEF users and external donor organizations to track and maintain donor reports. i was front end developer for this project, which was built with react. <br /><br />
        <b>built with:</b> react, redux, typescript <br /><br />
        <a href="https://github.com/unicef/donor-reporting-portal-frontend" target="_blank" rel="noreferrer"><b>github repo</b></a>
        </div>
      </div><hr />
      <div><br /></div>

      <div className="row">
        <div className="col-sm-4 col-sm-offset-2">
          <a href="https://etools.unicef.org/" target="_blank" rel="noreferrer">
            <img className="img-thumbnail" src="../../images/etools-screen-shot.png" alt="UNICEF eTools Screen Shot" />
          </a>
        </div>
        <div className="col-sm-4">
          <a href="https://etools.unicef.org/" target="_blank" rel="noreferrer"><h4>eTools - UNICEF</h4></a>
          i'm part of a team of developers who have created, enhanced, and maintained UNICEF's eTools progressive web application. eTools is a tool for UNICEF country offices to help manage partnerships with local governments, ngos, and institutions.<br /><br />
        <b>built with:</b> javascript, polymer, docker, circleci, polymer wct, dexie/indexeddb<br /><br />
        <a href="https://github.com/unicef/etools" target="_blank" rel="noreferrer"><b>github repo</b></a><br />
        <a href="/portfolio">portfolio</a>
        </div>
      </div><hr />
      <div><br /></div>
      
      <div className="row">
        <div className="col-sm-4 col-sm-offset-2">
          <a href="http://smart-tl.optimaldynamics.com/" target="_blank" rel="noreferrer">
            <img className="img-thumbnail" src="../../images/smart-tl-screen-shot.png" alt="Smart-TL Screen Shot" />
          </a>
        </div>
        <div className="col-sm-4">
          <a href="http://smart-tl.optimaldynamics.com/" target="_blank" rel="noreferrer"><h4>smart-tl landing page - Optimal Dynamics</h4></a>
          landing page for Optimal Dynamics' Smart-TL machine learning-driven logistics system<br /><br />
          <b>built with:</b> javascript, reactjs, gatsby, bootstrap<br /><br />
          <b>github repo</b> [private]
        </div>
      </div><hr />
      <div><br /></div>

      {/* <div className="row">
        <div className="col-sm-4 col-sm-offset-2">
          <a href="https://crisis-visualizer.herokuapp.com/" target="_blank" rel="noreferrer">
            <img className="img-thumbnail" src="../../images/crisis-screen-shot.jpg" alt="Crisis Project Screen Shot" />
          </a>
        </div>
        <div className="col-sm-4">
          <a href="https://crisis-visualizer.herokuapp.com/" target="_blank" rel="noreferrer"><h4>crisis visualizer - demo</h4></a>
          see how the size of the population where you live compares to the scale of crises around the world. we need a strong international development budget now more than ever. please make your voice heard.<br /><br />
        <b>built with:</b> javascript, reactjs, jquery<br /><br />
        <a href="https://github.com/drzackyll/syria-refugee-visualizer" target="_blank" rel="noreferrer"><b>github repo</b></a>
        </div>
      </div><hr />
      <div><br /></div> */}
    </div>
  )
}

export default Work
